
/*
 * the variable names and capnames are from the terminfo(5) man page
 */

module.exports = {
    // ==============
    // == BOOLEANS ==
    // ==============
    AUTO_LEFT_MARGIN:         'bw',
    AUTO_RIGHT_MARGIN:        'am',
    BACK_COLOR_ERASE:         'bce',
    CAN_CHANGE:               'ccc',
    CEOL_STANDOUT_GLITCH:     'xhp',
    COL_ADDR_GLITCH:          'xhpa',
    CPI_CHANGES_RES:          'cpix',
    CR_CANCELS_MICRO_MODE:    'crxm',
    DEST_TABS_MAGIC_SMSO:     'xt',
    EAT_NEWLINE_GLITCH:       'xenl',
    ERASE_OVERSTRIKE:         'eo',
    GENERIC_TYPE:             'gn',
    HARD_COPY:                'hc',
    HARD_CURSOR:              'chts',
    HAS_META_KEY:             'km',
    HAS_PRINT_WHEEL:          'daisy',
    HAS_STATUS_LINE:          'hs',
    HUE_LIGHTNESS_SATURATION: 'hls',
    INSERT_NULL_GLITCH:       'in',
    LPI_CHANGES_RES:          'lpix',
    MEMORY_ABOVE:             'da',
    MEMORY_BELOW:             'db',
    MOVE_INSERT_MODE:         'mir',
    MOVE_STANDOUT_MODE:       'msgr',
    NEEDS_XON_XOFF:           'nxon',
    NO_ESC_CTLC:              'xsb',
    NO_PAD_CHAR:              'npc',
    NON_DEST_SCROLL_REGION:   'ndscr',
    NON_REV_RMCUP:            'nrrmc',
    OVER_STRIKE:              'os',
    PRTR_SILENT:              'mc5i',
    ROW_ADDR_GLITCH:          'xvpa',
    SEMI_AUTO_RIGHT_MARGIN:   'sam',
    STATUS_LINE_ESC_OK:       'eslok',
    TILDE_GLITCH:             'hz',
    TRANSPARENT_UNDERLINE:    'ul',
    XON_XOFF:                 'xon',
    // =============
    // == NUMBERS ==
    // =============
    COLUMNS:              'cols',
    INIT_TABS:            'it',
    LABEL_HEIGHT:         'lh',
    LABEL_WIDTH:          'lw',
    LINES:                'lines',
    LINES_OF_MEMORY:      'lm',
    MAGIC_COOKIE_GLITCH:  'xmc',
    MAX_ATTRIBUTES:       'ma',
    MAX_COLORS:           'colors',
    MAX_PAIRS:            'pairs',
    MAXIMUM_WINDOWS:      'wnum',
    NO_COLOR_VIDEO:       'ncv',
    NUM_LABELS:           'nlab',
    PADDING_BAUD_RATE:    'pb',
    VIRTUAL_TERMINAL:     'vt',
    WIDTH_STATUS_LINE:    'wsl',
    BIT_IMAGE_ENTWINING:  'bitwin',
    BIT_IMAGE_TYPE:       'bitype',
    BUFFER_CAPACITY:      'bufsz',
    BUTTONS:              'btns',
    DOT_HORZ_SPACING:     'spinh',
    DOT_VERT_SPACING:     'spinv',
    MAX_MICRO_ADDRESS:    'maddr',
    MAX_MICRO_JUMP:       'mjump',
    MICRO_COL_SIZE:       'mcs',
    MICRO_LINE_SIZE:      'mls',
    NUMBER_OF_PINS:       'npins',
    OUTPUT_RES_CHAR:      'orc',
    OUTPUT_RES_HORZ_INCH: 'orhi',
    OUTPUT_RES_LINE:      'orl',
    OUTPUT_RES_VERT_INCH: 'orvi',
    PRINT_RATE:           'cps',
    WIDE_CHAR_SIZE:       'widcs',
    // =============
    // == STRINGS ==
    // =============
    ACS_CHARS:                 'acsc',
    BACK_TAB:                  'cbt',
    BELL:                      'bel',
    CARRIAGE_RETURN:           'cr',
    CHANGE_CHAR_PITCH:         'cpi',
    CHANGE_LINE_PITCH:         'lpi',
    CHANGE_RES_HORZ:           'chr',
    CHANGE_RES_VERT:           'cvr',
    CHANGE_SCROLL_REGION:      'csr',
    CHAR_PADDING:              'rmp',
    CLEAR_ALL_TABS:            'tbc',
    CLEAR_MARGINS:             'mgc',
    CLEAR_SCREEN:              'clear',
    CLR_BOL:                   'el1',
    CLR_EOL:                   'el',
    CLR_EOS:                   'ed',
    COLUMN_ADDRESS:            'hpa',
    COMMAND_CHARACTER:         'cmdch',
    CREATE_WINDOW:             'cwin',
    CURSOR_ADDRESS:            'cup',
    CURSOR_DOWN:               'cud1',
    CURSOR_HOME:               'home',
    CURSOR_INVISIBLE:          'civis',
    CURSOR_LEFT:               'cub1',
    CURSOR_MEM_ADDRESS:        'mrcup',
    CURSOR_NORMAL:             'cnorm',
    CURSOR_RIGHT:              'cuf1',
    CURSOR_TO_LL:              'll',
    CURSOR_UP:                 'cuu1',
    CURSOR_VISIBLE:            'cvvis',
    DEFINE_CHAR:               'defc',
    DELETE_CHARACTER:          'dch1',
    DELETE_LINE:               'dl1',
    DIAL_PHONE:                'dial',
    DIS_STATUS_LINE:           'dsl',
    DISPLAY_CLOCK:             'dclk',
    DOWN_HALF_LINE:            'hd',
    ENA_ACS:                   'enacs',
    ENTER_ALT_CHARSET_MODE:    'smacs',
    ENTER_AM_MODE:             'smam',
    ENTER_BLINK_MODE:          'blink',
    ENTER_BOLD_MODE:           'bold',
    ENTER_CA_MODE:             'smcup',
    ENTER_DELETE_MODE:         'smdc',
    ENTER_DIM_MODE:            'dim',
    ENTER_DOUBLEWIDE_MODE:     'swidm',
    ENTER_DRAFT_QUALITY:       'sdrfq',
    ENTER_INSERT_MODE:         'smir',
    ENTER_ITALICS_MODE:        'sitm',
    ENTER_LEFTWARD_MODE:       'slm',
    ENTER_MICRO_MODE:          'smicm',
    ENTER_NEAR_LETTER_QUALITY: 'snlq',
    ENTER_NORMAL_QUALITY:      'snrmq',
    ENTER_PROTECTED_MODE:      'prot',
    ENTER_REVERSE_MODE:        'rev',
    ENTER_SECURE_MODE:         'invis',
    ENTER_SHADOW_MODE:         'sshm',
    ENTER_STANDOUT_MODE:       'smso',
    ENTER_SUBSCRIPT_MODE:      'ssubm',
    ENTER_SUPERSCRIPT_MODE:    'ssupm',
    ENTER_UNDERLINE_MODE:      'smul',
    ENTER_UPWARD_MODE:         'sum',
    ENTER_XON_MODE:            'smxon',
    ERASE_CHARS:               'ech',
    EXIT_ALT_CHARSET_MODE:     'rmacs',
    EXIT_AM_MODE:              'rmam',
    EXIT_ATTRIBUTE_MODE:       'sgr0',
    EXIT_CA_MODE:              'rmcup',
    EXIT_DELETE_MODE:          'rmdc',
    EXIT_DOUBLEWIDE_MODE:      'rwidm',
    EXIT_INSERT_MODE:          'rmir',
    EXIT_ITALICS_MODE:         'ritm',
    EXIT_LEFTWARD_MODE:        'rlm',
    EXIT_MICRO_MODE:           'rmicm',
    EXIT_SHADOW_MODE:          'rshm',
    EXIT_STANDOUT_MODE:        'rmso',
    EXIT_SUBSCRIPT_MODE:       'rsubm',
    EXIT_SUPERSCRIPT_MODE:     'rsupm',
    EXIT_UNDERLINE_MODE:       'rmul',
    EXIT_UPWARD_MODE:          'rum',
    EXIT_XON_MODE:             'rmxon',
    FIXED_PAUSE:               'pause',
    FLASH_HOOK:                'hook',
    FLASH_SCREEN:              'flash',
    FORM_FEED:                 'ff',
    FROM_STATUS_LINE:          'fsl',
    GOTO_WINDOW:               'wingo',
    HANGUP:                    'hup',
    INIT_1STRING:              'is1',
    INIT_2STRING:              'is2',
    INIT_3STRING:              'is3',
    INIT_FILE:                 'if',
    INIT_PROG:                 'iprog',
    INITIALIZE_COLOR:          'initc',
    INITIALIZE_PAIR:           'initp',
    INSERT_CHARACTER:          'ich1',
    INSERT_LINE:               'il1',
    INSERT_PADDING:            'ip',
    KEY_A1:                    'ka1',
    KEY_A3:                    'ka3',
    KEY_B2:                    'kb2',
    KEY_BACKSPACE:             'kbs',
    KEY_BEG:                   'kbeg',
    KEY_BTAB:                  'kcbt',
    KEY_C1:                    'kc1',
    KEY_C3:                    'kc3',
    KEY_CANCEL:                'kcan',
    KEY_CATAB:                 'ktbc',
    KEY_CLEAR:                 'kclr',
    KEY_CLOSE:                 'kclo',
    KEY_COMMAND:               'kcmd',
    KEY_COPY:                  'kcpy',
    KEY_CREATE:                'kcrt',
    KEY_CTAB:                  'kctab',
    KEY_DC:                    'kdch1',
    KEY_DL:                    'kdl1',
    KEY_DOWN:                  'kcud1',
    KEY_EIC:                   'krmir',
    KEY_END:                   'kend',
    KEY_ENTER:                 'kent',
    KEY_EOL:                   'kel',
    KEY_EOS:                   'ked',
    KEY_EXIT:                  'kext',
    KEY_F0:                    'kf0',
    KEY_F1:                    'kf1',
    KEY_F10:                   'kf10',
    KEY_F11:                   'kf11',
    KEY_F12:                   'kf12',
    KEY_F13:                   'kf13',
    KEY_F14:                   'kf14',
    KEY_F15:                   'kf15',
    KEY_F16:                   'kf16',
    KEY_F17:                   'kf17',
    KEY_F18:                   'kf18',
    KEY_F19:                   'kf19',
    KEY_F2:                    'kf2',
    KEY_F20:                   'kf20',
    KEY_F21:                   'kf21',
    KEY_F22:                   'kf22',
    KEY_F23:                   'kf23',
    KEY_F24:                   'kf24',
    KEY_F25:                   'kf25',
    KEY_F26:                   'kf26',
    KEY_F27:                   'kf27',
    KEY_F28:                   'kf28',
    KEY_F29:                   'kf29',
    KEY_F3:                    'kf3',
    KEY_F30:                   'kf30',
    KEY_F31:                   'kf31',
    KEY_F32:                   'kf32',
    KEY_F33:                   'kf33',
    KEY_F34:                   'kf34',
    KEY_F35:                   'kf35',
    KEY_F36:                   'kf36',
    KEY_F37:                   'kf37',
    KEY_F38:                   'kf38',
    KEY_F39:                   'kf39',
    KEY_F4:                    'kf4',
    KEY_F40:                   'kf40',
    KEY_F41:                   'kf41',
    KEY_F42:                   'kf42',
    KEY_F43:                   'kf43',
    KEY_F44:                   'kf44',
    KEY_F45:                   'kf45',
    KEY_F46:                   'kf46',
    KEY_F47:                   'kf47',
    KEY_F48:                   'kf48',
    KEY_F49:                   'kf49',
    KEY_F5:                    'kf5',
    KEY_F50:                   'kf50',
    KEY_F51:                   'kf51',
    KEY_F52:                   'kf52',
    KEY_F53:                   'kf53',
    KEY_F54:                   'kf54',
    KEY_F55:                   'kf55',
    KEY_F56:                   'kf56',
    KEY_F57:                   'kf57',
    KEY_F58:                   'kf58',
    KEY_F59:                   'kf59',
    KEY_F6:                    'kf6',
    KEY_F60:                   'kf60',
    KEY_F61:                   'kf61',
    KEY_F62:                   'kf62',
    KEY_F63:                   'kf63',
    KEY_F7:                    'kf7',
    KEY_F8:                    'kf8',
    KEY_F9:                    'kf9',
    KEY_FIND:                  'kfnd',
    KEY_HELP:                  'khlp',
    KEY_HOME:                  'khome',
    KEY_IC:                    'kich1',
    KEY_IL:                    'kil1',
    KEY_LEFT:                  'kcub1',
    KEY_LL:                    'kll',
    KEY_MARK:                  'kmrk',
    KEY_MESSAGE:               'kmsg',
    KEY_MOVE:                  'kmov',
    KEY_NEXT:                  'knxt',
    KEY_NPAGE:                 'knp',
    KEY_OPEN:                  'kopn',
    KEY_OPTIONS:               'kopt',
    KEY_PPAGE:                 'kpp',
    KEY_PREVIOUS:              'kprv',
    KEY_PRINT:                 'kprt',
    KEY_REDO:                  'krdo',
    KEY_REFERENCE:             'kref',
    KEY_REFRESH:               'krfr',
    KEY_REPLACE:               'krpl',
    KEY_RESTART:               'krst',
    KEY_RESUME:                'kres',
    KEY_RIGHT:                 'kcuf1',
    KEY_SAVE:                  'ksav',
    KEY_SBEG:                  'kBEG',
    KEY_SCANCEL:               'kCAN',
    KEY_SCOMMAND:              'kCMD',
    KEY_SCOPY:                 'kCPY',
    KEY_SCREATE:               'kCRT',
    KEY_SDC:                   'kDC',
    KEY_SDL:                   'kDL',
    KEY_SELECT:                'kslt',
    KEY_SEND:                  'kEND',
    KEY_SEOL:                  'kEOL',
    KEY_SEXIT:                 'kEXT',
    KEY_SF:                    'kind',
    KEY_SFIND:                 'kFND',
    KEY_SHELP:                 'kHLP',
    KEY_SHOME:                 'kHOM',
    KEY_SIC:                   'kIC',
    KEY_SLEFT:                 'kLFT',
    KEY_SMESSAGE:              'kMSG',
    KEY_SMOVE:                 'kMOV',
    KEY_SNEXT:                 'kNXT',
    KEY_SOPTIONS:              'kOPT',
    KEY_SPREVIOUS:             'kPRV',
    KEY_SPRINT:                'kPRT',
    KEY_SR:                    'kri',
    KEY_SREDO:                 'kRDO',
    KEY_SREPLACE:              'kRPL',
    KEY_SRIGHT:                'kRIT',
    KEY_SRSUME:                'kRES',
    KEY_SSAVE:                 'kSAV',
    KEY_SSUSPEND:              'kSPD',
    KEY_STAB:                  'khts',
    KEY_SUNDO:                 'kUND',
    KEY_SUSPEND:               'kspd',
    KEY_UNDO:                  'kund',
    KEY_UP:                    'kcuu1',
    KEYPAD_LOCAL:              'rmkx',
    KEYPAD_XMIT:               'smkx',
    LAB_F0:                    'lf0',
    LAB_F1:                    'lf1',
    LAB_F10:                   'lf10',
    LAB_F2:                    'lf2',
    LAB_F3:                    'lf3',
    LAB_F4:                    'lf4',
    LAB_F5:                    'lf5',
    LAB_F6:                    'lf6',
    LAB_F7:                    'lf7',
    LAB_F8:                    'lf8',
    LAB_F9:                    'lf9',
    LABEL_FORMAT:              'fln',
    LABEL_OFF:                 'rmln',
    LABEL_ON:                  'smln',
    META_OFF:                  'rmm',
    META_ON:                   'smm',
    MICRO_COLUMN_ADDRESS:      'mhpa',
    MICRO_DOWN:                'mcud1',
    MICRO_LEFT:                'mcub1',
    MICRO_RIGHT:               'mcuf1',
    MICRO_ROW_ADDRESS:         'mvpa',
    MICRO_UP:                  'mcuu1',
    NEWLINE:                   'nel',
    ORDER_OF_PINS:             'porder',
    ORIG_COLORS:               'oc',
    ORIG_PAIR:                 'op',
    PAD_CHAR:                  'pad',
    PARM_DCH:                  'dch',
    PARM_DELETE_LINE:          'dl',
    PARM_DOWN_CURSOR:          'cud',
    PARM_DOWN_MICRO:           'mcud',
    PARM_ICH:                  'ich',
    PARM_INDEX:                'indn',
    PARM_INSERT_LINE:          'il',
    PARM_LEFT_CURSOR:          'cub',
    PARM_LEFT_MICRO:           'mcub',
    PARM_RIGHT_CURSOR:         'cuf',
    PARM_RIGHT_MICRO:          'mcuf',
    PARM_RINDEX:               'rin',
    PARM_UP_CURSOR:            'cuu',
    PARM_UP_MICRO:             'mcuu',
    PKEY_KEY:                  'pfkey',
    PKEY_LOCAL:                'pfloc',
    PKEY_XMIT:                 'pfx',
    PLAB_NORM:                 'pln',
    PRINT_SCREEN:              'mc0',
    PRTR_NON:                  'mc5p',
    PRTR_OFF:                  'mc4',
    PRTR_ON:                   'mc5',
    PULSE:                     'pulse',
    QUICK_DIAL:                'qdial',
    REMOVE_CLOCK:              'rmclk',
    REPEAT_CHAR:               'rep',
    REQ_FOR_INPUT:             'rfi',
    RESET_1STRING:             'rs1',
    RESET_2STRING:             'rs2',
    RESET_3STRING:             'rs3',
    RESET_FILE:                'rf',
    RESTORE_CURSOR:            'rc',
    ROW_ADDRESS:               'vpa',
    SAVE_CURSOR:               'sc',
    SCROLL_FORWARD:            'ind',
    SCROLL_REVERSE:            'ri',
    SELECT_CHAR_SET:           'scs',
    SET_ATTRIBUTES:            'sgr',
    SET_BACKGROUND:            'setb',
    SET_BOTTOM_MARGIN:         'smgb',
    SET_BOTTOM_MARGIN_PARM:    'smgbp',
    SET_CLOCK:                 'sclk',
    SET_COLOR_PAIR:            'scp',
    SET_FOREGROUND:            'setf',
    SET_LEFT_MARGIN:           'smgl',
    SET_LEFT_MARGIN_PARM:      'smglp',
    SET_RIGHT_MARGIN:          'smgr',
    SET_RIGHT_MARGIN_PARM:     'smgrp',
    SET_TAB:                   'hts',
    SET_TOP_MARGIN:            'smgt',
    SET_TOP_MARGIN_PARM:       'smgtp',
    SET_WINDOW:                'wind',
    START_BIT_IMAGE:           'sbim',
    START_CHAR_SET_DEF:        'scsd',
    STOP_BIT_IMAGE:            'rbim',
    STOP_CHAR_SET_DEF:         'rcsd',
    SUBSCRIPT_CHARACTERS:      'subcs',
    SUPERSCRIPT_CHARACTERS:    'supcs',
    TAB:                       'ht',
    THESE_CAUSE_CR:            'docr',
    TO_STATUS_LINE:            'tsl',
    TONE:                      'tone',
    UNDERLINE_CHAR:            'uc',
    UP_HALF_LINE:              'hu',
    USER0:                     'u0',
    USER1:                     'u1',
    USER2:                     'u2',
    USER3:                     'u3',
    USER4:                     'u4',
    USER5:                     'u5',
    USER6:                     'u6',
    USER7:                     'u7',
    USER8:                     'u8',
    USER9:                     'u9',
    WAIT_TONE:                 'wait',
    XOFF_CHARACTER:            'xoffc',
    XON_CHARACTER:             'xonc',
    ZERO_MOTION:               'zerom',
    ALT_SCANCODE_ESC:          'scesa',
    BIT_IMAGE_CARRIAGE_RETURN: 'bicr',
    BIT_IMAGE_NEWLINE:         'binel',
    BIT_IMAGE_REPEAT:          'birep',
    CHAR_SET_NAMES:            'csnm',
    CODE_SET_INIT:             'csin',
    COLOR_NAMES:               'colornm',
    DEFINE_BIT_IMAGE_REGION:   'defbi',
    DEVICE_TYPE:               'devt',
    DISPLAY_PC_CHAR:           'dispc',
    END_BIT_IMAGE_REGION:      'endbi',
    ENTER_PC_CHARSET_MODE:     'smpch',
    ENTER_SCANCODE_MODE:       'smsc',
    EXIT_PC_CHARSET_MODE:      'rmpch',
    EXIT_SCANCODE_MODE:        'rmsc',
    GET_MOUSE:                 'getm',
    KEY_MOUSE:                 'kmous',
    MOUSE_INFO:                'minfo',
    PC_TERM_OPTIONS:           'pctrm',
    PKEY_PLAB:                 'pfxl',
    REQ_MOUSE_POS:             'reqmp',
    SCANCODE_ESCAPE:           'scesc',
    SET0_DES_SEQ:              's0ds',
    SET1_DES_SEQ:              's1ds',
    SET2_DES_SEQ:              's2ds',
    SET3_DES_SEQ:              's3ds',
    SET_A_BACKGROUND:          'setab',
    SET_A_FOREGROUND:          'setaf',
    SET_COLOR_BAND:            'setcolor',
    SET_LR_MARGIN:             'smglr',
    SET_PAGE_LENGTH:           'slines',
    SET_TB_MARGIN:             'smgtb',
    ENTER_HORIZONTAL_HL_MODE:  'ehhlm',
    ENTER_LEFT_HL_MODE:        'elhlm',
    ENTER_LOW_HL_MODE:         'elohlm',
    ENTER_RIGHT_HL_MODE:       'erhlm',
    ENTER_TOP_HL_MODE:         'ethlm',
    ENTER_VERTICAL_HL_MODE:    'evhlm',
    SET_A_ATTRIBUTES:          'sgr1',
    SET_PGLEN_INCH:            'slength'
};

/*
 * the order of the variables are from the header file <term.h>
 */

module.exports.VARORDER = {
    booleans: [
        module.exports.AUTO_LEFT_MARGIN,
        module.exports.AUTO_RIGHT_MARGIN,
        module.exports.NO_ESC_CTLC,
        module.exports.CEOL_STANDOUT_GLITCH,
        module.exports.EAT_NEWLINE_GLITCH,
        module.exports.ERASE_OVERSTRIKE,
        module.exports.GENERIC_TYPE,
        module.exports.HARD_COPY,
        module.exports.HAS_META_KEY,
        module.exports.HAS_STATUS_LINE,
        module.exports.INSERT_NULL_GLITCH,
        module.exports.MEMORY_ABOVE,
        module.exports.MEMORY_BELOW,
        module.exports.MOVE_INSERT_MODE,
        module.exports.MOVE_STANDOUT_MODE,
        module.exports.OVER_STRIKE,
        module.exports.STATUS_LINE_ESC_OK,
        module.exports.DEST_TABS_MAGIC_SMSO,
        module.exports.TILDE_GLITCH,
        module.exports.TRANSPARENT_UNDERLINE,
        module.exports.XON_XOFF,
        module.exports.NEEDS_XON_XOFF,
        module.exports.PRTR_SILENT,
        module.exports.HARD_CURSOR,
        module.exports.NON_REV_RMCUP,
        module.exports.NO_PAD_CHAR,
        module.exports.NON_DEST_SCROLL_REGION,
        module.exports.CAN_CHANGE,
        module.exports.BACK_COLOR_ERASE,
        module.exports.HUE_LIGHTNESS_SATURATION,
        module.exports.COL_ADDR_GLITCH,
        module.exports.CR_CANCELS_MICRO_MODE,
        module.exports.HAS_PRINT_WHEEL,
        module.exports.ROW_ADDR_GLITCH,
        module.exports.SEMI_AUTO_RIGHT_MARGIN,
        module.exports.CPI_CHANGES_RES,
        module.exports.LPI_CHANGES_RES
    ],
    numbers: [
        module.exports.COLUMNS,
        module.exports.INIT_TABS,
        module.exports.LINES,
        module.exports.LINES_OF_MEMORY,
        module.exports.MAGIC_COOKIE_GLITCH,
        module.exports.PADDING_BAUD_RATE,
        module.exports.VIRTUAL_TERMINAL,
        module.exports.WIDTH_STATUS_LINE,
        module.exports.NUM_LABELS,
        module.exports.LABEL_HEIGHT,
        module.exports.LABEL_WIDTH,
        module.exports.MAX_ATTRIBUTES,
        module.exports.MAXIMUM_WINDOWS,
        module.exports.MAX_COLORS,
        module.exports.MAX_PAIRS,
        module.exports.NO_COLOR_VIDEO,
        module.exports.BUFFER_CAPACITY,
        module.exports.DOT_VERT_SPACING,
        module.exports.DOT_HORZ_SPACING,
        module.exports.MAX_MICRO_ADDRESS,
        module.exports.MAX_MICRO_JUMP,
        module.exports.MICRO_COL_SIZE,
        module.exports.MICRO_LINE_SIZE,
        module.exports.NUMBER_OF_PINS,
        module.exports.OUTPUT_RES_CHAR,
        module.exports.OUTPUT_RES_LINE,
        module.exports.OUTPUT_RES_HORZ_INCH,
        module.exports.OUTPUT_RES_VERT_INCH,
        module.exports.PRINT_RATE,
        module.exports.WIDE_CHAR_SIZE,
        module.exports.BUTTONS,
        module.exports.BIT_IMAGE_ENTWINING,
        module.exports.BIT_IMAGE_TYPE
    ],
    strings: [
        module.exports.BACK_TAB,
        module.exports.BELL,
        module.exports.CARRIAGE_RETURN,
        module.exports.CHANGE_SCROLL_REGION,
        module.exports.CLEAR_ALL_TABS,
        module.exports.CLEAR_SCREEN,
        module.exports.CLR_EOL,
        module.exports.CLR_EOS,
        module.exports.COLUMN_ADDRESS,
        module.exports.COMMAND_CHARACTER,
        module.exports.CURSOR_ADDRESS,
        module.exports.CURSOR_DOWN,
        module.exports.CURSOR_HOME,
        module.exports.CURSOR_INVISIBLE,
        module.exports.CURSOR_LEFT,
        module.exports.CURSOR_MEM_ADDRESS,
        module.exports.CURSOR_NORMAL,
        module.exports.CURSOR_RIGHT,
        module.exports.CURSOR_TO_LL,
        module.exports.CURSOR_UP,
        module.exports.CURSOR_VISIBLE,
        module.exports.DELETE_CHARACTER,
        module.exports.DELETE_LINE,
        module.exports.DIS_STATUS_LINE,
        module.exports.DOWN_HALF_LINE,
        module.exports.ENTER_ALT_CHARSET_MODE,
        module.exports.ENTER_BLINK_MODE,
        module.exports.ENTER_BOLD_MODE,
        module.exports.ENTER_CA_MODE,
        module.exports.ENTER_DELETE_MODE,
        module.exports.ENTER_DIM_MODE,
        module.exports.ENTER_INSERT_MODE,
        module.exports.ENTER_SECURE_MODE,
        module.exports.ENTER_PROTECTED_MODE,
        module.exports.ENTER_REVERSE_MODE,
        module.exports.ENTER_STANDOUT_MODE,
        module.exports.ENTER_UNDERLINE_MODE,
        module.exports.ERASE_CHARS,
        module.exports.EXIT_ALT_CHARSET_MODE,
        module.exports.EXIT_ATTRIBUTE_MODE,
        module.exports.EXIT_CA_MODE,
        module.exports.EXIT_DELETE_MODE,
        module.exports.EXIT_INSERT_MODE,
        module.exports.EXIT_STANDOUT_MODE,
        module.exports.EXIT_UNDERLINE_MODE,
        module.exports.FLASH_SCREEN,
        module.exports.FORM_FEED,
        module.exports.FROM_STATUS_LINE,
        module.exports.INIT_1STRING,
        module.exports.INIT_2STRING,
        module.exports.INIT_3STRING,
        module.exports.INIT_FILE,
        module.exports.INSERT_CHARACTER,
        module.exports.INSERT_LINE,
        module.exports.INSERT_PADDING,
        module.exports.KEY_BACKSPACE,
        module.exports.KEY_CATAB,
        module.exports.KEY_CLEAR,
        module.exports.KEY_CTAB,
        module.exports.KEY_DC,
        module.exports.KEY_DL,
        module.exports.KEY_DOWN,
        module.exports.KEY_EIC,
        module.exports.KEY_EOL,
        module.exports.KEY_EOS,
        module.exports.KEY_F0,
        module.exports.KEY_F1,
        module.exports.KEY_F10,
        module.exports.KEY_F2,
        module.exports.KEY_F3,
        module.exports.KEY_F4,
        module.exports.KEY_F5,
        module.exports.KEY_F6,
        module.exports.KEY_F7,
        module.exports.KEY_F8,
        module.exports.KEY_F9,
        module.exports.KEY_HOME,
        module.exports.KEY_IC,
        module.exports.KEY_IL,
        module.exports.KEY_LEFT,
        module.exports.KEY_LL,
        module.exports.KEY_NPAGE,
        module.exports.KEY_PPAGE,
        module.exports.KEY_RIGHT,
        module.exports.KEY_SF,
        module.exports.KEY_SR,
        module.exports.KEY_STAB,
        module.exports.KEY_UP,
        module.exports.KEYPAD_LOCAL,
        module.exports.KEYPAD_XMIT,
        module.exports.LAB_F0,
        module.exports.LAB_F1,
        module.exports.LAB_F10,
        module.exports.LAB_F2,
        module.exports.LAB_F3,
        module.exports.LAB_F4,
        module.exports.LAB_F5,
        module.exports.LAB_F6,
        module.exports.LAB_F7,
        module.exports.LAB_F8,
        module.exports.LAB_F9,
        module.exports.META_OFF,
        module.exports.META_ON,
        module.exports.NEWLINE,
        module.exports.PAD_CHAR,
        module.exports.PARM_DCH,
        module.exports.PARM_DELETE_LINE,
        module.exports.PARM_DOWN_CURSOR,
        module.exports.PARM_ICH,
        module.exports.PARM_INDEX,
        module.exports.PARM_INSERT_LINE,
        module.exports.PARM_LEFT_CURSOR,
        module.exports.PARM_RIGHT_CURSOR,
        module.exports.PARM_RINDEX,
        module.exports.PARM_UP_CURSOR,
        module.exports.PKEY_KEY,
        module.exports.PKEY_LOCAL,
        module.exports.PKEY_XMIT,
        module.exports.PRINT_SCREEN,
        module.exports.PRTR_OFF,
        module.exports.PRTR_ON,
        module.exports.REPEAT_CHAR,
        module.exports.RESET_1STRING,
        module.exports.RESET_2STRING,
        module.exports.RESET_3STRING,
        module.exports.RESET_FILE,
        module.exports.RESTORE_CURSOR,
        module.exports.ROW_ADDRESS,
        module.exports.SAVE_CURSOR,
        module.exports.SCROLL_FORWARD,
        module.exports.SCROLL_REVERSE,
        module.exports.SET_ATTRIBUTES,
        module.exports.SET_TAB,
        module.exports.SET_WINDOW,
        module.exports.TAB,
        module.exports.TO_STATUS_LINE,
        module.exports.UNDERLINE_CHAR,
        module.exports.UP_HALF_LINE,
        module.exports.INIT_PROG,
        module.exports.KEY_A1,
        module.exports.KEY_A3,
        module.exports.KEY_B2,
        module.exports.KEY_C1,
        module.exports.KEY_C3,
        module.exports.PRTR_NON,
        module.exports.CHAR_PADDING,
        module.exports.ACS_CHARS,
        module.exports.PLAB_NORM,
        module.exports.KEY_BTAB,
        module.exports.ENTER_XON_MODE,
        module.exports.EXIT_XON_MODE,
        module.exports.ENTER_AM_MODE,
        module.exports.EXIT_AM_MODE,
        module.exports.XON_CHARACTER,
        module.exports.XOFF_CHARACTER,
        module.exports.ENA_ACS,
        module.exports.LABEL_ON,
        module.exports.LABEL_OFF,
        module.exports.KEY_BEG,
        module.exports.KEY_CANCEL,
        module.exports.KEY_CLOSE,
        module.exports.KEY_COMMAND,
        module.exports.KEY_COPY,
        module.exports.KEY_CREATE,
        module.exports.KEY_END,
        module.exports.KEY_ENTER,
        module.exports.KEY_EXIT,
        module.exports.KEY_FIND,
        module.exports.KEY_HELP,
        module.exports.KEY_MARK,
        module.exports.KEY_MESSAGE,
        module.exports.KEY_MOVE,
        module.exports.KEY_NEXT,
        module.exports.KEY_OPEN,
        module.exports.KEY_OPTIONS,
        module.exports.KEY_PREVIOUS,
        module.exports.KEY_PRINT,
        module.exports.KEY_REDO,
        module.exports.KEY_REFERENCE,
        module.exports.KEY_REFRESH,
        module.exports.KEY_REPLACE,
        module.exports.KEY_RESTART,
        module.exports.KEY_RESUME,
        module.exports.KEY_SAVE,
        module.exports.KEY_SUSPEND,
        module.exports.KEY_UNDO,
        module.exports.KEY_SBEG,
        module.exports.KEY_SCANCEL,
        module.exports.KEY_SCOMMAND,
        module.exports.KEY_SCOPY,
        module.exports.KEY_SCREATE,
        module.exports.KEY_SDC,
        module.exports.KEY_SDL,
        module.exports.KEY_SELECT,
        module.exports.KEY_SEND,
        module.exports.KEY_SEOL,
        module.exports.KEY_SEXIT,
        module.exports.KEY_SFIND,
        module.exports.KEY_SHELP,
        module.exports.KEY_SHOME,
        module.exports.KEY_SIC,
        module.exports.KEY_SLEFT,
        module.exports.KEY_SMESSAGE,
        module.exports.KEY_SMOVE,
        module.exports.KEY_SNEXT,
        module.exports.KEY_SOPTIONS,
        module.exports.KEY_SPREVIOUS,
        module.exports.KEY_SPRINT,
        module.exports.KEY_SREDO,
        module.exports.KEY_SREPLACE,
        module.exports.KEY_SRIGHT,
        module.exports.KEY_SRSUME,
        module.exports.KEY_SSAVE,
        module.exports.KEY_SSUSPEND,
        module.exports.KEY_SUNDO,
        module.exports.REQ_FOR_INPUT,
        module.exports.KEY_F11,
        module.exports.KEY_F12,
        module.exports.KEY_F13,
        module.exports.KEY_F14,
        module.exports.KEY_F15,
        module.exports.KEY_F16,
        module.exports.KEY_F17,
        module.exports.KEY_F18,
        module.exports.KEY_F19,
        module.exports.KEY_F20,
        module.exports.KEY_F21,
        module.exports.KEY_F22,
        module.exports.KEY_F23,
        module.exports.KEY_F24,
        module.exports.KEY_F25,
        module.exports.KEY_F26,
        module.exports.KEY_F27,
        module.exports.KEY_F28,
        module.exports.KEY_F29,
        module.exports.KEY_F30,
        module.exports.KEY_F31,
        module.exports.KEY_F32,
        module.exports.KEY_F33,
        module.exports.KEY_F34,
        module.exports.KEY_F35,
        module.exports.KEY_F36,
        module.exports.KEY_F37,
        module.exports.KEY_F38,
        module.exports.KEY_F39,
        module.exports.KEY_F40,
        module.exports.KEY_F41,
        module.exports.KEY_F42,
        module.exports.KEY_F43,
        module.exports.KEY_F44,
        module.exports.KEY_F45,
        module.exports.KEY_F46,
        module.exports.KEY_F47,
        module.exports.KEY_F48,
        module.exports.KEY_F49,
        module.exports.KEY_F50,
        module.exports.KEY_F51,
        module.exports.KEY_F52,
        module.exports.KEY_F53,
        module.exports.KEY_F54,
        module.exports.KEY_F55,
        module.exports.KEY_F56,
        module.exports.KEY_F57,
        module.exports.KEY_F58,
        module.exports.KEY_F59,
        module.exports.KEY_F60,
        module.exports.KEY_F61,
        module.exports.KEY_F62,
        module.exports.KEY_F63,
        module.exports.CLR_BOL,
        module.exports.CLEAR_MARGINS,
        module.exports.SET_LEFT_MARGIN,
        module.exports.SET_RIGHT_MARGIN,
        module.exports.LABEL_FORMAT,
        module.exports.SET_CLOCK,
        module.exports.DISPLAY_CLOCK,
        module.exports.REMOVE_CLOCK,
        module.exports.CREATE_WINDOW,
        module.exports.GOTO_WINDOW,
        module.exports.HANGUP,
        module.exports.DIAL_PHONE,
        module.exports.QUICK_DIAL,
        module.exports.TONE,
        module.exports.PULSE,
        module.exports.FLASH_HOOK,
        module.exports.FIXED_PAUSE,
        module.exports.WAIT_TONE,
        module.exports.USER0,
        module.exports.USER1,
        module.exports.USER2,
        module.exports.USER3,
        module.exports.USER4,
        module.exports.USER5,
        module.exports.USER6,
        module.exports.USER7,
        module.exports.USER8,
        module.exports.USER9,
        module.exports.ORIG_PAIR,
        module.exports.ORIG_COLORS,
        module.exports.INITIALIZE_COLOR,
        module.exports.INITIALIZE_PAIR,
        module.exports.SET_COLOR_PAIR,
        module.exports.SET_FOREGROUND,
        module.exports.SET_BACKGROUND,
        module.exports.CHANGE_CHAR_PITCH,
        module.exports.CHANGE_LINE_PITCH,
        module.exports.CHANGE_RES_HORZ,
        module.exports.CHANGE_RES_VERT,
        module.exports.DEFINE_CHAR,
        module.exports.ENTER_DOUBLEWIDE_MODE,
        module.exports.ENTER_DRAFT_QUALITY,
        module.exports.ENTER_ITALICS_MODE,
        module.exports.ENTER_LEFTWARD_MODE,
        module.exports.ENTER_MICRO_MODE,
        module.exports.ENTER_NEAR_LETTER_QUALITY,
        module.exports.ENTER_NORMAL_QUALITY,
        module.exports.ENTER_SHADOW_MODE,
        module.exports.ENTER_SUBSCRIPT_MODE,
        module.exports.ENTER_SUPERSCRIPT_MODE,
        module.exports.ENTER_UPWARD_MODE,
        module.exports.EXIT_DOUBLEWIDE_MODE,
        module.exports.EXIT_ITALICS_MODE,
        module.exports.EXIT_LEFTWARD_MODE,
        module.exports.EXIT_MICRO_MODE,
        module.exports.EXIT_SHADOW_MODE,
        module.exports.EXIT_SUBSCRIPT_MODE,
        module.exports.EXIT_SUPERSCRIPT_MODE,
        module.exports.EXIT_UPWARD_MODE,
        module.exports.MICRO_COLUMN_ADDRESS,
        module.exports.MICRO_DOWN,
        module.exports.MICRO_LEFT,
        module.exports.MICRO_RIGHT,
        module.exports.MICRO_ROW_ADDRESS,
        module.exports.MICRO_UP,
        module.exports.ORDER_OF_PINS,
        module.exports.PARM_DOWN_MICRO,
        module.exports.PARM_LEFT_MICRO,
        module.exports.PARM_RIGHT_MICRO,
        module.exports.PARM_UP_MICRO,
        module.exports.SELECT_CHAR_SET,
        module.exports.SET_BOTTOM_MARGIN,
        module.exports.SET_BOTTOM_MARGIN_PARM,
        module.exports.SET_LEFT_MARGIN_PARM,
        module.exports.SET_RIGHT_MARGIN_PARM,
        module.exports.SET_TOP_MARGIN,
        module.exports.SET_TOP_MARGIN_PARM,
        module.exports.START_BIT_IMAGE,
        module.exports.START_CHAR_SET_DEF,
        module.exports.STOP_BIT_IMAGE,
        module.exports.STOP_CHAR_SET_DEF,
        module.exports.SUBSCRIPT_CHARACTERS,
        module.exports.SUPERSCRIPT_CHARACTERS,
        module.exports.THESE_CAUSE_CR,
        module.exports.ZERO_MOTION,
        module.exports.CHAR_SET_NAMES,
        module.exports.KEY_MOUSE,
        module.exports.MOUSE_INFO,
        module.exports.REQ_MOUSE_POS,
        module.exports.GET_MOUSE,
        module.exports.SET_A_FOREGROUND,
        module.exports.SET_A_BACKGROUND,
        module.exports.PKEY_PLAB,
        module.exports.DEVICE_TYPE,
        module.exports.CODE_SET_INIT,
        module.exports.SET0_DES_SEQ,
        module.exports.SET1_DES_SEQ,
        module.exports.SET2_DES_SEQ,
        module.exports.SET3_DES_SEQ,
        module.exports.SET_LR_MARGIN,
        module.exports.SET_TB_MARGIN,
        module.exports.BIT_IMAGE_REPEAT,
        module.exports.BIT_IMAGE_NEWLINE,
        module.exports.BIT_IMAGE_CARRIAGE_RETURN,
        module.exports.COLOR_NAMES,
        module.exports.DEFINE_BIT_IMAGE_REGION,
        module.exports.END_BIT_IMAGE_REGION,
        module.exports.SET_COLOR_BAND,
        module.exports.SET_PAGE_LENGTH,
        module.exports.DISPLAY_PC_CHAR,
        module.exports.ENTER_PC_CHARSET_MODE,
        module.exports.EXIT_PC_CHARSET_MODE,
        module.exports.ENTER_SCANCODE_MODE,
        module.exports.EXIT_SCANCODE_MODE,
        module.exports.PC_TERM_OPTIONS,
        module.exports.SCANCODE_ESCAPE,
        module.exports.ALT_SCANCODE_ESC,
        module.exports.ENTER_HORIZONTAL_HL_MODE,
        module.exports.ENTER_LEFT_HL_MODE,
        module.exports.ENTER_LOW_HL_MODE,
        module.exports.ENTER_RIGHT_HL_MODE,
        module.exports.ENTER_TOP_HL_MODE,
        module.exports.ENTER_VERTICAL_HL_MODE,
        module.exports.SET_A_ATTRIBUTES,
        module.exports.SET_PGLEN_INCH
    ]
};
